linters:
  enable:
    - contextcheck
    - gci
    - gofumpt
    - gosimple
    - ineffassign
    - misspell
    - nonamedreturns
    - staticcheck
  disable:
    - errcheck

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/containernetworking)

run:
  skip-dirs:
    - vendor
