language: go
sudo: required
dist: trusty

go:
  - 1.6.x
  - 1.7.x
  - tip

env:
  global:
  - TOOLS_CMD=golang.org/x/tools/cmd
  - PATH=$GOROOT/bin:$PATH
  - GO15VENDOREXPERIMENT=1
  matrix:
  - TARGET=amd64
  - TARGET=arm
  - TARGET=arm64
  - TARGET=ppc64le
  - TARGET=s390x

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
  exclude:
  - go: tip
    env: TARGET=arm
  - go: tip
    env: TARGET=arm64
  - go: tip
    env: TARGET=ppc64le
  - go: tip
    env: TARGET=s390x
  - go: 1.6.x
    env: TARGET=s390x


install:
 - go get ${TOOLS_CMD}/cover
 - go get github.com/modocache/gover
 - go get github.com/mattn/goveralls

script:
 - >
    if [ "${TARGET}" == "amd64" ]; then
      GOARCH="${TARGET}" ./test;
    else
      GOARCH="${TARGET}" ./build;
    fi

notifications:
  email: false

git:
  depth: 9999999
