language: go
sudo: required

go:
  - 1.4
  - 1.5.3
  - 1.6

env:
  global:
    - TOOLS_CMD=golang.org/x/tools/cmd
    - PATH=$GOROOT/bin:$PATH

install:
 - go get ${TOOLS_CMD}/vet
 - go get ${TOOLS_CMD}/cover
 - go get github.com/modocache/gover
 - go get github.com/mattn/goveralls

script:
 - ./test

notifications:
  email: false
