language: go
sudo: required
dist: trusty

go:
  - 1.7.x
  - 1.8.x

env:
  global:
  - PATH=$GOROOT/bin:$PATH
  matrix:
  - TARGET=amd64
  - TARGET=arm
  - TARGET=arm64
  - TARGET=ppc64le
  - TARGET=s390x

matrix:
  fast_finish: true

install:
 - |
   go get github.com/containernetworking/cni || true
   pushd ../cni
     GOARCH="${TARGET}" ./build.sh
   popd

script:
 - |
   if [ "${TARGET}" == "amd64" ]; then
     CNI_PATH="$(cd ../cni/bin && pwd)" GOARCH="${TARGET}" ./test
   else
     GOARCH="${TARGET}" ./build
   fi

notifications:
  email: false

git:
  depth: 9999999
